version: '3.8'

services:
  llm-agent:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    ports:
      - "7860:7860"  # Gradio UI
      - "6006:6006"  # Telemetry/Phoenix
    volumes:
      - ./data:/home/data
      - ./scripts:/home/scripts
